apiVersion: v1
kind: Pod

metadata:
  name: frontend-pod
  labels:
    app: frontend

spec:
  containers:
  - name: frontend
    image: ramanachandrakiranreddy/k8s-webapp:v1

    ports:
    - containerPort: 80