apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: frontend-rs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: ramanachandrakiranreddy/k8s-webapp:v1

        ports:
        - containerPort: 80